### ISSUE TITLE
web debug and Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by agelospanagiotakis** [RajTechnologiesPvtLtd/flutter-moonlight#7]
I get an error 

gestureSettings: DeviceGestureSettings(touchSlop: null), displayFeatures: [])):
Unsupported operation: Platform._operatingSystem
The relevant error-causing widget was:
  Scaffold
Scaffold:file:///home/agelos/Desktop/development/contribute/flutter-moonlight/lib/views/home_view.dart:14:12
home_view.dart:14

**Comment by bhargavraviya** [comment]
> I get an error
> 
> gestureSettings: DeviceGestureSettings(touchSlop: null), displayFeatures: [])): Unsupported operation: Platform._operatingSystem The relevant error-causing widget was: Scaffold Scaffold:file:///home/agelos/Desktop/development/contribute/flutter-moonlight/lib/views/home_view.dart:14:12 home_view.dart:14
@agelospanagiotakis 
Please provide me with more information about the error, such as when it occurred.

**Comment by agelospanagiotakis** [comment]
this is happening when compiling  for target: web
not android

**Comment by bhargavraviya** [comment]
> this is happening when compiling for target: web not android

Please check it again. I have solved this issue, but some features are not working.

@agelospanagiotakis
